version: '3.8'
services:
  wire-pod:
    hostname: escapepod
    image: ghcr.io/kercre123/wire-pod:main
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8084:8084
    volumes:
      - wire-pod-data:/chipper/
      - wire-pod-model:/vosk/
      - ./plugins:/chipper/plugins

  wire-pod-mdns:
    build: ./
    restart: unless-stopped
    network_mode: "host"
    command: ["--srvIP", "specify ip address of wire-pod"]

volumes:
  wire-pod-data:
    driver: local
  wire-pod-model:
    driver: local
